development:
  adapter: postgresql
  encoding: unicode
  database: bloccit_development
  pool: 5
  username: kc
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: bloccit_test
  pool: 5
  username: kc
  password: 